language: android
jdk: oraclejdk8
sudo: false

notifications:
  email:
    - suprinya.pa@centrilliontech.co.th
    -
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-22
    - android-24
    - android-26
    - android-27
    - sys-img-armeabi-v7a-android-22
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository