language: android
sudo: required
jdk: oraclejdk8

addons:
  apt:
    packages:
      - lynx

notifications:
  email:
    - suprinya.pa@centrilliontech.co.th

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_EMU_API_LEVEL=22

    #matrix:
    #- ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
    #- ANDROID_SDKS=android-24,sysimg-24  ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a
    #- ANDROID_SDKS=android-27,sysimg-27  ANDROID_TARGET=android-27  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-27
    - android-22
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-22
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - openssl aes-256-cbc -K $encrypted_2e23d3804d07_key -iv $encrypted_2e23d3804d07_iv -in automatedtest-ci-demo-firebase-adminsdk-iwoq0-659c2cbb4f.json.enc -out automatedtest-ci-demo-firebase-adminsdk-iwoq0-659c2cbb4f.json -d
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/google-cloud-sdk/

install: true

before_script: chmod +x gradlew

jobs:
  include:
    - stage: "Tests"                                        # naming the Tests stage
      name: "Unit Tests - API"                              # names the first Tests stage job
      script: ./gradlew testApiDebugUnitTest --stacktrace
    #    - script: ./gradlew testMockDebugUnitTest --stacktrace
    #      name: "Unit Tests - MOCK"                             # names the second Tests stage job
    #    - before_script:
    #        - android list targets
    #        - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi $ANDROID_ABI -c 100M
    #        - emulator -avd test -no-audio -no-window &
    #        - android-wait-for-emulator
    #        - adb shell input keyevent 82 &
    #      script: ./gradlew connectedApiDebugAndroidTest --stacktrace
    #      name: "Instrumentation Tests -  API - MainActivity"   # names the third Tests stage job
    - before_script:
        # gcloud
        - gcloud version || true
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        # Add gcloud to $PATH
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud version
        # Add gcloud auth
        - gcloud auth activate-service-account firebase-adminsdk-iwoq0@automatedtest-ci-demo.iam.gserviceaccount.com --key-file=automatedtest-ci-demo-firebase-adminsdk-iwoq0-659c2cbb4f.json --project=automatedtest-ci-demo
        # Add gcloud services enable
        - gcloud services enable toolresults.googleapis.com
      script:
        - ./gradlew assembleMockDebug
        - ./gradlew assembleMockDebugAndroidTest
        - gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/mock/debug/app-mock-debug.apk --test app/build/outputs/apk/androidTest/mock/debug/app-mock-debug-androidTest.apk --device model=NexusLowRes,version=26
        #- gcloud firebase test android run --type robo --app app/build/outputs/apk/mock/debug/app-mock-debug.apk --device model=NexusLowRes,version=28 --device model=NexusLowRes,version=25 --device model=shamu,version=21
      name: "Firebase Test Lab - Instrumentation Tests"

  #script:
  #- ./gradlew clean test
  #- ./gradlew clean build
  #- ./gradlew connectedApiDebugAndroidTest
  #- ./gradlew connectedMockDebugAndroidTest
  #- ./gradlew testApiDebugUnitTest --stacktrace
  #- ./gradlew testMockDebugUnitTest --stacktrace

after_failure:
  - if [ -f /home/travis/build/Dewan1991/automatedtest-ci-demo/app/build/reports/tests/*/index.html ]; then lynx -dump /home/travis/build/Dewan1991/automatedtest-ci-demo/app/build/reports/tests/*/index.html; fi